name: fastapi creation

on:
  push:
    branches:
      - main
    paths:
      - 'fastapi/**'
  pull_request:
    branches:
      - main
    paths:
      - 'fastapi/**'

jobs: 
  build-deploy:
    runs-on: ubuntu-latest  
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: print hello
        run: echo "Hello world"
      